export { analyzeFile } from './astAnalyzer'
export type { CodeFeature } from './astAnalyzer'
export { aggregateAnalyses, calculateBrowserSupport } from './browserCompat'
export type { BrowserSupport, FileAnalysis, MinVersions } from './browserCompat'
export { buildFileTree, getFileTree, IGNORE_PATTERNS, SCAN_PATTERNS, scanFiles } from './fileScanner'
export type { FileEntry, ScanResult, TreeNode } from './fileScanner'
